import 'package:language_code/src/store_code.dart';

import 'language_codes.dart';

/// Supported language codes for Google Play and Apple App Store metadata.
///
/// Use [playStore] and [appStore] when you only need the supported code sets,
/// or [bothStores] when you need to translate a base language into the exact
/// store-specific codes.
class StoreSupportedCodes {
  StoreSupportedCodes._();

  /// Language codes supported by Google Play.
  ///
  /// Legacy Hebrew locale codes were renamed from `iw_IL` to `he_IL`.
  static const Set<LanguageCodes> playStore = {
    LanguageCodes.af,
    LanguageCodes.am,
    LanguageCodes.ar,
    LanguageCodes.az_AZ,
    LanguageCodes.be,
    LanguageCodes.bn_BD,
    LanguageCodes.bg,
    LanguageCodes.ca,
    LanguageCodes.cs_CZ,
    LanguageCodes.da_DK,
    LanguageCodes.de_DE,
    LanguageCodes.el_GR,
    LanguageCodes.en_AU,
    LanguageCodes.en_CA,
    LanguageCodes.en_GB,
    LanguageCodes.en_IN,
    LanguageCodes.en_SG,
    LanguageCodes.en_US,
    LanguageCodes.et,
    LanguageCodes.eu_ES,
    LanguageCodes.fil,
    LanguageCodes.fi_FI,
    LanguageCodes.fr_CA,
    LanguageCodes.fr_FR,
    LanguageCodes.gl_ES,
    LanguageCodes.hi_IN,
    LanguageCodes.hr,
    LanguageCodes.hu_HU,
    LanguageCodes.hy_AM,
    LanguageCodes.he_IL,
    LanguageCodes.id,
    LanguageCodes.is_IS,
    LanguageCodes.it_IT,
    LanguageCodes.ja_JP,
    LanguageCodes.ka_GE,
    LanguageCodes.km_KH,
    LanguageCodes.kn_IN,
    LanguageCodes.ko_KR,
    LanguageCodes.ky_KG,
    LanguageCodes.lo_LA,
    LanguageCodes.lt,
    LanguageCodes.lv,
    LanguageCodes.mk_MK,
    LanguageCodes.ml_IN,
    LanguageCodes.mn_MN,
    LanguageCodes.mr_IN,
    LanguageCodes.ms,
    LanguageCodes.my_MM,
    LanguageCodes.ne_NP,
    LanguageCodes.nl_NL,
    LanguageCodes.no_NO,
    LanguageCodes.fa,
    LanguageCodes.pl_PL,
    LanguageCodes.pt_BR,
    LanguageCodes.pt_PT,
    LanguageCodes.rm,
    LanguageCodes.ro,
    LanguageCodes.ru_RU,
    LanguageCodes.si_LK,
    LanguageCodes.sk,
    LanguageCodes.sl,
    LanguageCodes.sr,
    LanguageCodes.es_419,
    LanguageCodes.es_ES,
    LanguageCodes.es_US,
    LanguageCodes.sw,
    LanguageCodes.sv_SE,
    LanguageCodes.ta_IN,
    LanguageCodes.te_IN,
    LanguageCodes.th,
    LanguageCodes.tr_TR,
    LanguageCodes.uk,
    LanguageCodes.vi,
    LanguageCodes.zh_CN,
    LanguageCodes.zh_HK,
    LanguageCodes.zh_TW,
    LanguageCodes.zu,
  };

  /// Language codes supported by the Apple App Store.
  static const Set<LanguageCodes> appStore = {
    LanguageCodes.ar_SA,
    LanguageCodes.bn_BD,
    LanguageCodes.ca,
    LanguageCodes.cs,
    LanguageCodes.da,
    LanguageCodes.de_DE,
    LanguageCodes.el,
    LanguageCodes.en_AU,
    LanguageCodes.en_CA,
    LanguageCodes.en_GB,
    LanguageCodes.en_US,
    LanguageCodes.fi,
    LanguageCodes.fr_CA,
    LanguageCodes.fr_FR,
    LanguageCodes.gu_IN,
    LanguageCodes.he,
    LanguageCodes.hi,
    LanguageCodes.hr,
    LanguageCodes.hu,
    LanguageCodes.id,
    LanguageCodes.it,
    LanguageCodes.ja,
    LanguageCodes.kn_IN,
    LanguageCodes.ko,
    LanguageCodes.ml_IN,
    LanguageCodes.ms,
    LanguageCodes.mr_IN,
    LanguageCodes.no,
    LanguageCodes.nl_NL,
    LanguageCodes.or_IN,
    LanguageCodes.pa_IN,
    LanguageCodes.pl,
    LanguageCodes.pt_BR,
    LanguageCodes.pt_PT,
    LanguageCodes.ro,
    LanguageCodes.ru,
    LanguageCodes.sl_SI,
    LanguageCodes.es_MX,
    LanguageCodes.es_ES,
    LanguageCodes.sk,
    LanguageCodes.sv,
    LanguageCodes.ta_IN,
    LanguageCodes.te_IN,
    LanguageCodes.th,
    LanguageCodes.tr,
    LanguageCodes.uk,
    LanguageCodes.ur_PK,
    LanguageCodes.vi,
    LanguageCodes.zh_Hans,
    LanguageCodes.zh_Hant,
  };

  /// Base language codes mapped to the matching Play Store and App Store codes.
  ///
  /// The keys are normalized two-letter language codes. Each value contains the
  /// supported store-specific variants for that language.
  static final Map<LanguageCodes, Set<StoreCode>> bothStores = {
    LanguageCodes.ar: {StoreCode(LanguageCodes.ar, LanguageCodes.ar_SA)},
    LanguageCodes.bn: {StoreCode(LanguageCodes.bn_BD, LanguageCodes.bn_BD)},
    LanguageCodes.ca: {StoreCode(LanguageCodes.ca, LanguageCodes.ca)},
    LanguageCodes.cs: {StoreCode(LanguageCodes.cs_CZ, LanguageCodes.cs)},
    LanguageCodes.da: {StoreCode(LanguageCodes.da_DK, LanguageCodes.da)},
    LanguageCodes.de: {StoreCode(LanguageCodes.de_DE, LanguageCodes.de_DE)},
    LanguageCodes.el: {StoreCode(LanguageCodes.el_GR, LanguageCodes.el)},
    LanguageCodes.en: {
      StoreCode(LanguageCodes.en_AU, LanguageCodes.en_AU),
      StoreCode(LanguageCodes.en_CA, LanguageCodes.en_CA),
      StoreCode(LanguageCodes.en_GB, LanguageCodes.en_GB),
      StoreCode(LanguageCodes.en_US, LanguageCodes.en_US),
    },
    LanguageCodes.es: {
      StoreCode(LanguageCodes.es_ES, LanguageCodes.es_ES),
      StoreCode(LanguageCodes.es_419, LanguageCodes.es_MX),
      StoreCode(LanguageCodes.es_US, LanguageCodes.es_MX),
    },
    LanguageCodes.fi: {StoreCode(LanguageCodes.fi_FI, LanguageCodes.fi)},
    LanguageCodes.fr: {
      StoreCode(LanguageCodes.fr_CA, LanguageCodes.fr_CA),
      StoreCode(LanguageCodes.fr_FR, LanguageCodes.fr_FR),
    },
    LanguageCodes.he: {StoreCode(LanguageCodes.he_IL, LanguageCodes.he)},
    LanguageCodes.hi: {StoreCode(LanguageCodes.hi_IN, LanguageCodes.hi)},
    LanguageCodes.hr: {StoreCode(LanguageCodes.hr, LanguageCodes.hr)},
    LanguageCodes.hu: {StoreCode(LanguageCodes.hu_HU, LanguageCodes.hu)},
    LanguageCodes.id: {StoreCode(LanguageCodes.id, LanguageCodes.id)},
    LanguageCodes.it: {StoreCode(LanguageCodes.it_IT, LanguageCodes.it)},
    LanguageCodes.ja: {StoreCode(LanguageCodes.ja_JP, LanguageCodes.ja)},
    LanguageCodes.kn: {StoreCode(LanguageCodes.kn_IN, LanguageCodes.kn_IN)},
    LanguageCodes.ko: {StoreCode(LanguageCodes.ko_KR, LanguageCodes.ko)},
    LanguageCodes.ml: {StoreCode(LanguageCodes.ml_IN, LanguageCodes.ml_IN)},
    LanguageCodes.mr: {StoreCode(LanguageCodes.mr_IN, LanguageCodes.mr_IN)},
    LanguageCodes.ms: {StoreCode(LanguageCodes.ms, LanguageCodes.ms)},
    LanguageCodes.nl: {StoreCode(LanguageCodes.nl_NL, LanguageCodes.nl_NL)},
    LanguageCodes.no: {StoreCode(LanguageCodes.no_NO, LanguageCodes.no)},
    LanguageCodes.pl: {StoreCode(LanguageCodes.pl_PL, LanguageCodes.pl)},
    LanguageCodes.pt: {
      StoreCode(LanguageCodes.pt_BR, LanguageCodes.pt_BR),
      StoreCode(LanguageCodes.pt_PT, LanguageCodes.pt_PT),
    },
    LanguageCodes.ro: {StoreCode(LanguageCodes.ro, LanguageCodes.ro)},
    LanguageCodes.ru: {StoreCode(LanguageCodes.ru_RU, LanguageCodes.ru)},
    LanguageCodes.sk: {StoreCode(LanguageCodes.sk, LanguageCodes.sk)},
    LanguageCodes.sl: {StoreCode(LanguageCodes.sl, LanguageCodes.sl_SI)},
    LanguageCodes.sv: {StoreCode(LanguageCodes.sv_SE, LanguageCodes.sv)},
    LanguageCodes.ta: {StoreCode(LanguageCodes.ta_IN, LanguageCodes.ta_IN)},
    LanguageCodes.te: {StoreCode(LanguageCodes.te_IN, LanguageCodes.te_IN)},
    LanguageCodes.th: {StoreCode(LanguageCodes.th, LanguageCodes.th)},
    LanguageCodes.tr: {StoreCode(LanguageCodes.tr_TR, LanguageCodes.tr)},
    LanguageCodes.uk: {StoreCode(LanguageCodes.uk, LanguageCodes.uk)},
    LanguageCodes.vi: {StoreCode(LanguageCodes.vi, LanguageCodes.vi)},
    LanguageCodes.zh: {
      StoreCode(LanguageCodes.zh_CN, LanguageCodes.zh_Hans),
      StoreCode(LanguageCodes.zh_TW, LanguageCodes.zh_Hant),
      StoreCode(LanguageCodes.zh_HK, LanguageCodes.zh_Hant),
    },
  };
}
